# Generated by Django 2.1.3 on 2018-12-16 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название игры')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('video', models.URLField(blank=True, verbose_name='Ссылка на видео YouTube')),
                ('num_players', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во игроков')),
                ('age_players', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Допустимый возраст')),
                ('year', models.DateField(blank=True, verbose_name='Дата выпуска')),
                ('language', models.CharField(blank=True, choices=[('RU', 'Русский'), ('EN', 'Английский')], max_length=50, verbose_name='Язык')),
                ('owner', models.CharField(blank=True, max_length=50, verbose_name='Разработчик')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
                ('slug', models.SlugField(default=None, unique=True, verbose_name='ЧПУ')),
            ],
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Жанр игры')),
            ],
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Платформа игры')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(blank=True, to='games.GamePlatform', verbose_name='Платформа'),
        ),
    ]
