# Generated by Django 2.1.3 on 2018-12-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20181216_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Adam', to='games.Tag'),
        ),
    ]
