# Generated by Django 2.1.3 on 2018-12-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20181218_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, to='games.Tag'),
        ),
    ]
