# Generated by Django 2.1.3 on 2018-12-24 14:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('games', '0008_gamecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags_taggit',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
