# Generated by Django 2.1.3 on 2018-12-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_tags_taggit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
