# Generated by Django 2.1.3 on 2018-12-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название организации')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес')),
                ('site', models.CharField(max_length=50, verbose_name='Сайт')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('rating', models.CharField(max_length=50, verbose_name='Рейтинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='ЧПУ')),
                ('delivery', models.BooleanField(default=False, verbose_name='Возможность выезда на дом')),
            ],
        ),
    ]
