# Generated by Django 2.1.3 on 2018-12-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20181219_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='games',
        ),
    ]
