# Generated by Django 2.1.3 on 2018-12-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_club_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='metro',
            field=models.CharField(default='Укажите нахвание станции', max_length=50, verbose_name='Ближайшее метро'),
        ),
    ]
