# Generated by Django 2.1.3 on 2018-12-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20181219_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='metro',
        ),
    ]
