# Generated by Django 2.1.3 on 2018-12-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_remove_club_metro'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='metro',
            field=models.CharField(default='метро', max_length=50, verbose_name='Ближайшее метро'),
        ),
    ]
