# Generated by Django 2.1.3 on 2018-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20181218_0610'),
        ('clubs', '0010_club_metro'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='games',
            field=models.ManyToManyField(blank=True, to='games.Game', verbose_name='Список игр клуба'),
        ),
    ]
